name: CodeTrybe Invitation
description: Become a part of CodeTrybe's growing network of developers and tech enthusiasts.
title: "Invite me to CodeTrybe"
labels: [Join CodeTrybe]
body:
  - type: input
    id: name
    attributes:
      label: Name
      description: Enter your name here
      placeholder: e.g Gekko Wrld
    validations:
      required: true
  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Please tell us a little bit about yourself and why you would like to join the CodeTrybe community. For example, you could mention any relevant experience you have, what programming languages or technologies you are interested in, or what you hope to gain by being a member of the community.
    validations:
      required: true
