name: List Contributors

on:
  push:
  pull_request:
  issues:
  issue_comment:
  pull_request_review_comment:
    types: [created, edited, deleted]
  pull_request_review:
    types: [submitted, edited, dismissed]

jobs:
  list-contributors:
    runs-on: ubuntu-latest
    steps:
      - name: Install jq
        run: sudo apt-get update && sudo apt-get -y install jq

      - name: Install octokit/rest
        run: npm install @octokit/rest@19.0.7

      - name: Get Contributors
        id: contributors
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const contributors = {};
            const octokit = require('@octokit/rest')();
            octokit.authenticate({
              type: 'token',
              token: process.env.GITHUB_TOKEN
            });
            const { data: repositories } = await octokit.repos.listForOrg({
              org: codetrybe,
              per_page: 100
            });
            for (const repo of repositories) {
              const { data: contributorsData } = await octokit.repos.listContributors({
                owner: codetrybe,
                repo: repo.name,
                per_page: 100
              });
              for (const contributor of contributorsData) {
                const { login, html_url } = contributor;
                if (!contributors[login]) {
                  contributors[login] = html_url;
                }
              }
            }
            return JSON.stringify(contributors);

      - name: Sort Contributors
        run: |
          jq -r 'keys[]' contributors.json | sort -u > sorted-contributors.txt
          mv sorted-contributors.txt contributors.txt

      - name: Update README
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'Update contributors list'
          file_pattern: 'README.md'
          commit_options: '--no-verify'
