name: List Contributors

on:
  push:
  pull_request:
  issues:
  issue_comment:
  pull_request_review_comment:
    types: [created, edited, deleted]
  pull_request_review:
    types: [submitted, edited, dismissed]

jobs:
  list-contributors:
    runs-on: ubuntu-latest
    steps:
      - name: Install jq
        run: sudo apt-get update && sudo apt-get -y install jq

      - name: Install isomorphic-fetch
        run: npm install isomorphic-fetch

      - name: Get Contributors
        id: contributors
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const contributors = {};
            const fetch = require('isomorphic-fetch');
            const headers = {
              'Authorization': `Bearer ${process.env.GITHUB_TOKEN}`,
              'Content-Type': 'application/json'
            };
            const requestOptions = {
              method: 'GET',
              headers
            };
            const response = await fetch('https://api.github.com/orgs/codetrybe/repos?per_page=100', requestOptions);
            const repositories = await response.json();
            for (const repo of repositories) {
              const url = `https://api.github.com/repos/codetrybe/${repo.name}/contributors?per_page=100`;
              const response = await fetch(url, requestOptions);
              const contributorsData = await response.json();
              for (const contributor of contributorsData) {
                const { login, html_url } = contributor;
                if (!contributors[login]) {
                  contributors[login] = html_url;
                }name: List Contributors

                on:
                  push:
                  pull_request:
                  issues:
                  issue_comment:
                  pull_request_review_comment:
                    types: [created, edited, deleted]
                  pull_request_review:
                    types: [submitted, edited, dismissed]
                
                jobs:
                  list-contributors:
                    runs-on: ubuntu-latest
                    steps:
                      - name: Install jq
                        run: sudo apt-get update && sudo apt-get -y install jq
                
                      - name: Install isomorphic-fetch
                        run: npm install isomorphic-fetch
                
                      - name: Get Contributors
                        id: contributors
                        uses: actions/github-script@v4
                        with:
                          github-token: ${{ secrets.GITHUB_TOKEN }}
                          script: |
                            const contributors = {};
                            const fetch = require('isomorphic-fetch');
                            const headers = {
                              'Authorization': `Bearer ${process.env.GITHUB_TOKEN}`,
                              'Content-Type': 'application/json'
                            };
                            const requestOptions = {
                              method: 'GET',
                              headers
                            };
                            const response = await fetch('https://api.github.com/orgs/codetrybe/repos?per_page=100', requestOptions);
                            const repositories = await response.json();
                            for (const repo of repositories) {
                              const url = `https://api.github.com/repos/codetrybe/${repo.name}/contributors?per_page=100`;
                              const response = await fetch(url, requestOptions);
                              const contributorsData = await response.json();
                              for (const contributor of contributorsData) {
                                const { login, html_url } = contributor;
                                if (!contributors[login]) {
                                  contributors[login] = html_url;
                                }
                              }
                            }
                            return JSON.stringify(contributors);
                
                      - name: Sort Contributors
                        run: |
                          jq -r 'keys[]' contributors.json | sort -u > sorted-contributors.txt
                          mv sorted-contributors.txt contributors.txt
                
                      - name: Update README
                        uses: stefanzweifel/git-auto-commit-action@v4
                        with:
                          commit_message: 'Update contributors list'
                          file_pattern: 'README.md'
                          commit_options: '--no-verify'
                
              }
            }
            return JSON.stringify(contributors);

      - name: Sort Contributors
        run: |
          jq -r 'keys[]' contributors.json | sort -u > sorted-contributors.txt
          mv sorted-contributors.txt contributors.txt

      - name: Update README
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'Update contributors list'
          file_pattern: 'README.md'
          commit_options: '--no-verify'
