on:
  issues:
    types: [labeled]

jobs:
  automate_invite:
    runs-on: ubuntu-latest
    steps:
      - name: Join CodeTrybe
        uses: vj-abigo/invite-on-label@v1.4
        with:
          organization: codetrybe
          label: Join CodeTrybe
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          comment: "<b>Invitation sent to join CodeTrybe (ALX SWE). Welcome to the community 🎉</b><br>Don't forget to make the Community public on your profile, so it appears on your GitHub profile for everyone else to see. You can do this by finding your name in the GitHub organisation list and change the dropdown to public https://github.com/orgs/codetrybe/people<br><br><b>HAPPY CODING!</b><br>"
        env:
          INVITE_TOKEN: ${{ secrets.INVITE_TOKEN }}
